name: Deploy Documentation to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby for Asciidoctor
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Install Asciidoctor
        run: gem install asciidoctor asciidoctor-diagram

      - name: Extract project version from pom.xml
        run: echo "PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Build Asciidoc documentation
        run: asciidoctor -r asciidoctor-diagram -b html5 ./docs/*.adoc -D output/v${{ env.PROJECT_VERSION }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output/v${{ env.PROJECT_VERSION }}
